# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'delta.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QGroupBox, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QSlider, QSpinBox, QTextBrowser,
    QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(1361, 798)
        self.serial_group = QGroupBox(Widget)
        self.serial_group.setObjectName(u"serial_group")
        self.serial_group.setGeometry(QRect(10, 10, 321, 281))
        self.label = QLabel(self.serial_group)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(15, 30, 81, 21))
        self.com = QComboBox(self.serial_group)
        self.com.setObjectName(u"com")
        self.com.setGeometry(QRect(90, 30, 140, 22))
        self.pushButton = QPushButton(self.serial_group)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(240, 30, 71, 52))
        self.textBrowser_2 = QTextBrowser(self.serial_group)
        self.textBrowser_2.setObjectName(u"textBrowser_2")
        self.textBrowser_2.setGeometry(QRect(15, 125, 295, 141))
        self.mqtt_topic_input = QLineEdit(self.serial_group)
        self.mqtt_topic_input.setObjectName(u"mqtt_topic_input")
        self.mqtt_topic_input.setGeometry(QRect(20, 60, 201, 25))
        self.mqtt_topic_input.setStyleSheet(u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)")
        self.subscribe_button = QPushButton(self.serial_group)
        self.subscribe_button.setObjectName(u"subscribe_button")
        self.subscribe_button.setGeometry(QRect(20, 90, 89, 25))
        self.subscribe_button.setStyleSheet(u"background-color: hsla(123, 75.50%, 68.00%, 0.25); border-radius: 3px; border: 3px solid hsla(123, 75.50%, 68.00%, 0.25)")
        self.stop_subscription_button = QPushButton(self.serial_group)
        self.stop_subscription_button.setObjectName(u"stop_subscription_button")
        self.stop_subscription_button.setGeometry(QRect(120, 90, 89, 25))
        self.stop_subscription_button.setStyleSheet(u"background-color: hsla(14, 83.40%, 59.80%, 0.25); border-radius: 3px; border: 3px solid hsla(14, 83.40%, 59.80%, 0.25)")
        self.clear_mqtt_messages_button = QPushButton(self.serial_group)
        self.clear_mqtt_messages_button.setObjectName(u"clear_mqtt_messages_button")
        self.clear_mqtt_messages_button.setGeometry(QRect(220, 90, 89, 25))
        self.clear_mqtt_messages_button.setStyleSheet(u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)")
        self.vision_group = QGroupBox(Widget)
        self.vision_group.setObjectName(u"vision_group")
        self.vision_group.setGeometry(QRect(10, 300, 321, 481))
        self.label_4 = QLabel(self.vision_group)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(15, 30, 100, 22))
        self.camera_selector = QComboBox(self.vision_group)
        self.camera_selector.setObjectName(u"camera_selector")
        self.camera_selector.setGeometry(QRect(110, 30, 191, 22))
        self.cameraButton1 = QPushButton(self.vision_group)
        self.cameraButton1.setObjectName(u"cameraButton1")
        self.cameraButton1.setGeometry(QRect(40, 70, 100, 25))
        self.cameraButton2 = QPushButton(self.vision_group)
        self.cameraButton2.setObjectName(u"cameraButton2")
        self.cameraButton2.setEnabled(False)
        self.cameraButton2.setGeometry(QRect(180, 70, 100, 25))
        self.cameraview = QLabel(self.vision_group)
        self.cameraview.setObjectName(u"cameraview")
        self.cameraview.setGeometry(QRect(15, 110, 291, 211))
        self.cameraview.setAlignment(Qt.AlignCenter)
        self.simulator_group = QGroupBox(self.vision_group)
        self.simulator_group.setObjectName(u"simulator_group")
        self.simulator_group.setGeometry(QRect(20, 340, 281, 131))
        self.simulator_enable_checkbox = QCheckBox(self.simulator_group)
        self.simulator_enable_checkbox.setObjectName(u"simulator_enable_checkbox")
        self.simulator_enable_checkbox.setGeometry(QRect(10, 40, 120, 20))
        self.simulator_enable_checkbox.setChecked(False)
        self.open_simulator_button = QPushButton(self.simulator_group)
        self.open_simulator_button.setObjectName(u"open_simulator_button")
        self.open_simulator_button.setGeometry(QRect(10, 80, 120, 25))
        self.update_simulator_button = QPushButton(self.simulator_group)
        self.update_simulator_button.setObjectName(u"update_simulator_button")
        self.update_simulator_button.setGeometry(QRect(140, 80, 120, 25))
        self.calibration_group = QGroupBox(Widget)
        self.calibration_group.setObjectName(u"calibration_group")
        self.calibration_group.setGeometry(QRect(340, 10, 281, 281))
        self.label_trans_x = QLabel(self.calibration_group)
        self.label_trans_x.setObjectName(u"label_trans_x")
        self.label_trans_x.setGeometry(QRect(20, 30, 100, 20))
        self.trans_x = QDoubleSpinBox(self.calibration_group)
        self.trans_x.setObjectName(u"trans_x")
        self.trans_x.setGeometry(QRect(130, 30, 120, 22))
        self.trans_x.setMinimum(-2000.000000000000000)
        self.trans_x.setMaximum(2000.000000000000000)
        self.label_trans_y = QLabel(self.calibration_group)
        self.label_trans_y.setObjectName(u"label_trans_y")
        self.label_trans_y.setGeometry(QRect(20, 60, 100, 20))
        self.trans_y = QDoubleSpinBox(self.calibration_group)
        self.trans_y.setObjectName(u"trans_y")
        self.trans_y.setGeometry(QRect(130, 60, 120, 22))
        self.trans_y.setMinimum(-2000.000000000000000)
        self.trans_y.setMaximum(2000.000000000000000)
        self.label_trans_z = QLabel(self.calibration_group)
        self.label_trans_z.setObjectName(u"label_trans_z")
        self.label_trans_z.setGeometry(QRect(20, 90, 100, 20))
        self.trans_z = QDoubleSpinBox(self.calibration_group)
        self.trans_z.setObjectName(u"trans_z")
        self.trans_z.setGeometry(QRect(130, 90, 120, 22))
        self.trans_z.setMinimum(-2000.000000000000000)
        self.trans_z.setMaximum(2000.000000000000000)
        self.label_trans_r = QLabel(self.calibration_group)
        self.label_trans_r.setObjectName(u"label_trans_r")
        self.label_trans_r.setGeometry(QRect(20, 130, 110, 20))
        self.trans_r = QDoubleSpinBox(self.calibration_group)
        self.trans_r.setObjectName(u"trans_r")
        self.trans_r.setGeometry(QRect(130, 130, 120, 22))
        self.trans_r.setMinimum(-180.000000000000000)
        self.trans_r.setMaximum(180.000000000000000)
        self.label_trans_p = QLabel(self.calibration_group)
        self.label_trans_p.setObjectName(u"label_trans_p")
        self.label_trans_p.setGeometry(QRect(20, 160, 110, 20))
        self.trans_p = QDoubleSpinBox(self.calibration_group)
        self.trans_p.setObjectName(u"trans_p")
        self.trans_p.setGeometry(QRect(130, 160, 120, 22))
        self.trans_p.setMinimum(-180.000000000000000)
        self.trans_p.setMaximum(180.000000000000000)
        self.label_trans_y_2 = QLabel(self.calibration_group)
        self.label_trans_y_2.setObjectName(u"label_trans_y_2")
        self.label_trans_y_2.setGeometry(QRect(20, 190, 110, 20))
        self.trans_y_2 = QDoubleSpinBox(self.calibration_group)
        self.trans_y_2.setObjectName(u"trans_y_2")
        self.trans_y_2.setGeometry(QRect(130, 190, 120, 22))
        self.trans_y_2.setMinimum(-180.000000000000000)
        self.trans_y_2.setMaximum(180.000000000000000)
        self.apply_transform_button = QPushButton(self.calibration_group)
        self.apply_transform_button.setObjectName(u"apply_transform_button")
        self.apply_transform_button.setGeometry(QRect(40, 230, 200, 30))
        self.robot_control_group = QGroupBox(Widget)
        self.robot_control_group.setObjectName(u"robot_control_group")
        self.robot_control_group.setGeometry(QRect(340, 300, 601, 481))
        self.pushButton_3 = QPushButton(self.robot_control_group)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(450, 20, 61, 41))
        self.pushButton_2 = QPushButton(self.robot_control_group)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(520, 20, 61, 41))
        self.label_21 = QLabel(self.robot_control_group)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(292, 75, 41, 21))
        self.v = QSlider(self.robot_control_group)
        self.v.setObjectName(u"v")
        self.v.setGeometry(QRect(298, 110, 22, 121))
        self.v.setValue(50)
        self.v.setOrientation(Qt.Vertical)
        self.pushButton_4 = QPushButton(self.robot_control_group)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(350, 120, 100, 31))
        self.pushButton_5 = QPushButton(self.robot_control_group)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(480, 120, 100, 31))
        self.pushButton_6 = QPushButton(self.robot_control_group)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(160, 75, 100, 31))
        self.inch_group = QGroupBox(self.robot_control_group)
        self.inch_group.setObjectName(u"inch_group")
        self.inch_group.setGeometry(QRect(10, 130, 271, 91))
        self.pushButton_8 = QPushButton(self.inch_group)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(10, 42, 31, 31))
        self.pushButton_9 = QPushButton(self.inch_group)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(50, 42, 31, 31))
        self.pushButton_10 = QPushButton(self.inch_group)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(100, 42, 31, 31))
        self.pushButton_11 = QPushButton(self.inch_group)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(140, 42, 31, 31))
        self.pushButton_12 = QPushButton(self.inch_group)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(190, 42, 31, 31))
        self.pushButton_13 = QPushButton(self.inch_group)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(230, 42, 31, 31))
        self.jog_sequence_group = QGroupBox(self.robot_control_group)
        self.jog_sequence_group.setObjectName(u"jog_sequence_group")
        self.jog_sequence_group.setGeometry(QRect(10, 230, 271, 231))
        self.start_point_label = QLabel(self.jog_sequence_group)
        self.start_point_label.setObjectName(u"start_point_label")
        self.start_point_label.setGeometry(QRect(10, 30, 100, 20))
        self.start_x_spinbox = QDoubleSpinBox(self.jog_sequence_group)
        self.start_x_spinbox.setObjectName(u"start_x_spinbox")
        self.start_x_spinbox.setGeometry(QRect(10, 57, 81, 31))
        self.start_x_spinbox.setMinimum(-150.000000000000000)
        self.start_x_spinbox.setMaximum(150.000000000000000)
        self.start_y_spinbox = QDoubleSpinBox(self.jog_sequence_group)
        self.start_y_spinbox.setObjectName(u"start_y_spinbox")
        self.start_y_spinbox.setGeometry(QRect(95, 57, 81, 31))
        self.start_y_spinbox.setMinimum(-150.000000000000000)
        self.start_y_spinbox.setMaximum(150.000000000000000)
        self.start_z_spinbox = QDoubleSpinBox(self.jog_sequence_group)
        self.start_z_spinbox.setObjectName(u"start_z_spinbox")
        self.start_z_spinbox.setGeometry(QRect(180, 57, 81, 31))
        self.start_z_spinbox.setMinimum(-99999.000000000000000)
        self.start_z_spinbox.setMaximum(999999.000000000000000)
        self.start_z_spinbox.setValue(-410.000000000000000)
        self.end_point_label = QLabel(self.jog_sequence_group)
        self.end_point_label.setObjectName(u"end_point_label")
        self.end_point_label.setGeometry(QRect(10, 97, 100, 20))
        self.end_x_spinbox = QDoubleSpinBox(self.jog_sequence_group)
        self.end_x_spinbox.setObjectName(u"end_x_spinbox")
        self.end_x_spinbox.setGeometry(QRect(10, 127, 81, 31))
        self.end_x_spinbox.setMinimum(-150.000000000000000)
        self.end_x_spinbox.setMaximum(150.000000000000000)
        self.end_y_spinbox = QDoubleSpinBox(self.jog_sequence_group)
        self.end_y_spinbox.setObjectName(u"end_y_spinbox")
        self.end_y_spinbox.setGeometry(QRect(95, 127, 81, 31))
        self.end_y_spinbox.setMinimum(-150.000000000000000)
        self.end_y_spinbox.setMaximum(150.000000000000000)
        self.end_z_spinbox = QDoubleSpinBox(self.jog_sequence_group)
        self.end_z_spinbox.setObjectName(u"end_z_spinbox")
        self.end_z_spinbox.setGeometry(QRect(180, 127, 81, 31))
        self.end_z_spinbox.setMinimum(-99999.000000000000000)
        self.end_z_spinbox.setMaximum(99999.000000000000000)
        self.end_z_spinbox.setValue(-410.000000000000000)
        self.run_jog_sequence_button = QPushButton(self.jog_sequence_group)
        self.run_jog_sequence_button.setObjectName(u"run_jog_sequence_button")
        self.run_jog_sequence_button.setGeometry(QRect(10, 180, 241, 31))
        self.motor_debug_group = QGroupBox(self.robot_control_group)
        self.motor_debug_group.setObjectName(u"motor_debug_group")
        self.motor_debug_group.setGeometry(QRect(340, 180, 261, 71))
        self.pushButton_14 = QPushButton(self.motor_debug_group)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(10, 30, 31, 31))
        self.pushButton_15 = QPushButton(self.motor_debug_group)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(50, 30, 31, 31))
        self.pushButton_16 = QPushButton(self.motor_debug_group)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(90, 30, 31, 31))
        self.pushButton_17 = QPushButton(self.motor_debug_group)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(130, 30, 31, 31))
        self.pushButton_18 = QPushButton(self.motor_debug_group)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(170, 30, 31, 31))
        self.pushButton_19 = QPushButton(self.motor_debug_group)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(210, 30, 31, 31))
        self.kinematics_group = QGroupBox(self.robot_control_group)
        self.kinematics_group.setObjectName(u"kinematics_group")
        self.kinematics_group.setGeometry(QRect(300, 260, 271, 201))
        self.label_fk = QLabel(self.kinematics_group)
        self.label_fk.setObjectName(u"label_fk")
        self.label_fk.setGeometry(QRect(10, 30, 141, 20))
        self.ik_x = QDoubleSpinBox(self.kinematics_group)
        self.ik_x.setObjectName(u"ik_x")
        self.ik_x.setGeometry(QRect(10, 70, 81, 25))
        self.ik_x.setMinimum(-150.000000000000000)
        self.ik_x.setMaximum(150.000000000000000)
        self.ik_y = QDoubleSpinBox(self.kinematics_group)
        self.ik_y.setObjectName(u"ik_y")
        self.ik_y.setGeometry(QRect(100, 70, 81, 25))
        self.ik_y.setMinimum(-150.000000000000000)
        self.ik_y.setMaximum(150.000000000000000)
        self.ik_z = QDoubleSpinBox(self.kinematics_group)
        self.ik_z.setObjectName(u"ik_z")
        self.ik_z.setGeometry(QRect(190, 70, 71, 25))
        self.ik_z.setMinimum(-610.000000000000000)
        self.ik_z.setMaximum(-410.000000000000000)
        self.solve_ik_button = QPushButton(self.kinematics_group)
        self.solve_ik_button.setObjectName(u"solve_ik_button")
        self.solve_ik_button.setGeometry(QRect(10, 110, 251, 30))
        self.ik_result_label = QLabel(self.kinematics_group)
        self.ik_result_label.setObjectName(u"ik_result_label")
        self.ik_result_label.setGeometry(QRect(10, 155, 231, 31))
        self.ik_result_label.setStyleSheet(u"font-size: 15px;")
        self.vision_dynamic_checkbox = QCheckBox(self.robot_control_group)
        self.vision_dynamic_checkbox.setObjectName(u"vision_dynamic_checkbox")
        self.vision_dynamic_checkbox.setGeometry(QRect(320, 35, 120, 20))
        self.vision_dynamic_checkbox.setChecked(False)
        self.comboBox = QComboBox(self.robot_control_group)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(20, 75, 100, 31))
        self.comboBox.setStyleSheet(u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)")
        self.visualization_checkbox = QCheckBox(self.robot_control_group)
        self.visualization_checkbox.setObjectName(u"visualization_checkbox")
        self.visualization_checkbox.setGeometry(QRect(20, 35, 131, 20))
        self.visualization_checkbox.setChecked(False)
        self.color_comboBox = QComboBox(self.robot_control_group)
        self.color_comboBox.setObjectName(u"color_comboBox")
        self.color_comboBox.setGeometry(QRect(480, 75, 100, 31))
        self.color_comboBox.setStyleSheet(u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)")
        self.shape_comboBox = QComboBox(self.robot_control_group)
        self.shape_comboBox.setObjectName(u"shape_comboBox")
        self.shape_comboBox.setGeometry(QRect(350, 75, 100, 31))
        self.shape_comboBox.setStyleSheet(u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)")
        self.pushButton_7 = QPushButton(self.robot_control_group)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(160, 30, 101, 31))
        self.status_group = QGroupBox(Widget)
        self.status_group.setObjectName(u"status_group")
        self.status_group.setGeometry(QRect(630, 10, 311, 241))
        self.label_9 = QLabel(self.status_group)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 30, 121, 21))
        self.label_10 = QLabel(self.status_group)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 60, 21, 21))
        self.textBrowser_3 = QTextBrowser(self.status_group)
        self.textBrowser_3.setObjectName(u"textBrowser_3")
        self.textBrowser_3.setGeometry(QRect(30, 55, 71, 31))
        self.label_12 = QLabel(self.status_group)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(110, 60, 21, 21))
        self.textBrowser_4 = QTextBrowser(self.status_group)
        self.textBrowser_4.setObjectName(u"textBrowser_4")
        self.textBrowser_4.setGeometry(QRect(130, 55, 71, 31))
        self.label_11 = QLabel(self.status_group)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(210, 60, 21, 21))
        self.textBrowser_5 = QTextBrowser(self.status_group)
        self.textBrowser_5.setObjectName(u"textBrowser_5")
        self.textBrowser_5.setGeometry(QRect(230, 55, 71, 31))
        self.label_13 = QLabel(self.status_group)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 110, 121, 21))
        self.label_14 = QLabel(self.status_group)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 140, 21, 21))
        self.textBrowser_6 = QTextBrowser(self.status_group)
        self.textBrowser_6.setObjectName(u"textBrowser_6")
        self.textBrowser_6.setGeometry(QRect(30, 135, 71, 31))
        self.label_16 = QLabel(self.status_group)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(110, 140, 21, 21))
        self.textBrowser_7 = QTextBrowser(self.status_group)
        self.textBrowser_7.setObjectName(u"textBrowser_7")
        self.textBrowser_7.setGeometry(QRect(130, 135, 71, 31))
        self.label_15 = QLabel(self.status_group)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(210, 140, 21, 21))
        self.textBrowser_8 = QTextBrowser(self.status_group)
        self.textBrowser_8.setObjectName(u"textBrowser_8")
        self.textBrowser_8.setGeometry(QRect(230, 135, 71, 31))
        self.calibrationStatus = QLabel(Widget)
        self.calibrationStatus.setObjectName(u"calibrationStatus")
        self.calibrationStatus.setGeometry(QRect(630, 260, 311, 30))
        self.writing_group = QGroupBox(Widget)
        self.writing_group.setObjectName(u"writing_group")
        self.writing_group.setGeometry(QRect(950, 10, 361, 771))
        self.terminal_output = QTextBrowser(self.writing_group)
        self.terminal_output.setObjectName(u"terminal_output")
        self.terminal_output.setGeometry(QRect(10, 29, 341, 201))
        self.writing_control_label = QLabel(self.writing_group)
        self.writing_control_label.setObjectName(u"writing_control_label")
        self.writing_control_label.setGeometry(QRect(10, 240, 80, 20))
        self.input_method_label = QLabel(self.writing_group)
        self.input_method_label.setObjectName(u"input_method_label")
        self.input_method_label.setGeometry(QRect(10, 270, 60, 20))
        self.input_method = QComboBox(self.writing_group)
        self.input_method.setObjectName(u"input_method")
        self.input_method.setGeometry(QRect(90, 270, 100, 25))
        self.text_input_label = QLabel(self.writing_group)
        self.text_input_label.setObjectName(u"text_input_label")
        self.text_input_label.setGeometry(QRect(200, 270, 60, 20))
        self.text_input = QLineEdit(self.writing_group)
        self.text_input.setObjectName(u"text_input")
        self.text_input.setGeometry(QRect(280, 270, 70, 25))
        self.text_input.setAlignment(Qt.AlignCenter)
        self.font_size_label = QLabel(self.writing_group)
        self.font_size_label.setObjectName(u"font_size_label")
        self.font_size_label.setGeometry(QRect(10, 305, 60, 20))
        self.font_size = QSpinBox(self.writing_group)
        self.font_size.setObjectName(u"font_size")
        self.font_size.setGeometry(QRect(90, 305, 101, 25))
        self.font_size.setAlignment(Qt.AlignCenter)
        self.font_size.setMinimum(10)
        self.font_size.setMaximum(100)
        self.font_size.setValue(30)
        self.writing_area_label = QLabel(self.writing_group)
        self.writing_area_label.setObjectName(u"writing_area_label")
        self.writing_area_label.setGeometry(QRect(200, 305, 71, 20))
        self.writing_area = QSpinBox(self.writing_group)
        self.writing_area.setObjectName(u"writing_area")
        self.writing_area.setGeometry(QRect(280, 305, 70, 25))
        self.writing_area.setAlignment(Qt.AlignCenter)
        self.writing_area.setMinimum(50)
        self.writing_area.setMaximum(300)
        self.writing_area.setValue(150)
        self.z_height_label = QLabel(self.writing_group)
        self.z_height_label.setObjectName(u"z_height_label")
        self.z_height_label.setGeometry(QRect(10, 340, 70, 20))
        self.z_height = QDoubleSpinBox(self.writing_group)
        self.z_height.setObjectName(u"z_height")
        self.z_height.setGeometry(QRect(90, 340, 101, 25))
        self.z_height.setAlignment(Qt.AlignCenter)
        self.z_height.setMinimum(-610.000000000000000)
        self.z_height.setMaximum(-410.000000000000000)
        self.z_height.setSingleStep(5.000000000000000)
        self.z_height.setValue(-500.000000000000000)
        self.writing_speed_label = QLabel(self.writing_group)
        self.writing_speed_label.setObjectName(u"writing_speed_label")
        self.writing_speed_label.setGeometry(QRect(200, 340, 60, 20))
        self.writing_speed = QSpinBox(self.writing_group)
        self.writing_speed.setObjectName(u"writing_speed")
        self.writing_speed.setGeometry(QRect(280, 340, 70, 25))
        self.writing_speed.setAlignment(Qt.AlignCenter)
        self.writing_speed.setMinimum(1)
        self.writing_speed.setMaximum(10)
        self.writing_speed.setValue(5)
        self.use_handwriting_button = QPushButton(self.writing_group)
        self.use_handwriting_button.setObjectName(u"use_handwriting_button")
        self.use_handwriting_button.setGeometry(QRect(10, 380, 75, 30))
        self.preview_button = QPushButton(self.writing_group)
        self.preview_button.setObjectName(u"preview_button")
        self.preview_button.setGeometry(QRect(100, 380, 75, 30))
        self.start_writing_button = QPushButton(self.writing_group)
        self.start_writing_button.setObjectName(u"start_writing_button")
        self.start_writing_button.setGeometry(QRect(190, 380, 75, 30))
        self.stop_writing_button = QPushButton(self.writing_group)
        self.stop_writing_button.setObjectName(u"stop_writing_button")
        self.stop_writing_button.setGeometry(QRect(280, 380, 75, 30))
        self.clear_canvas_button = QPushButton(self.writing_group)
        self.clear_canvas_button.setObjectName(u"clear_canvas_button")
        self.clear_canvas_button.setGeometry(QRect(10, 420, 341, 30))
        self.writing_canvas_label = QLabel(self.writing_group)
        self.writing_canvas_label.setObjectName(u"writing_canvas_label")
        self.writing_canvas_label.setGeometry(QRect(10, 460, 200, 20))
        self.writing_status = QLabel(self.writing_group)
        self.writing_status.setObjectName(u"writing_status")
        self.writing_status.setGeometry(QRect(10, 740, 341, 20))

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Delta\u673a\u5668\u4eba\u63a7\u5236\u5668", None))
        self.serial_group.setTitle(QCoreApplication.translate("Widget", u"\u4e32\u53e3\u63a7\u5236", None))
        self.label.setText(QCoreApplication.translate("Widget", u"\u4e32\u53e3\u9009\u62e9", None))
        self.pushButton.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton.setText(QCoreApplication.translate("Widget", u"\u8fde\u63a5", None))
        self.textBrowser_2.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.subscribe_button.setText(QCoreApplication.translate("Widget", u"\u8ba2\u9605\u8bdd\u9898", None))
        self.stop_subscription_button.setText(QCoreApplication.translate("Widget", u"\u505c\u6b62\u8ba2\u9605", None))
        self.clear_mqtt_messages_button.setText(QCoreApplication.translate("Widget", u"\u6e05\u7a7a\u6d88\u606f", None))
        self.vision_group.setTitle(QCoreApplication.translate("Widget", u"\u89c6\u89c9\u63a7\u5236", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"\u6444\u50cf\u5934\u9009\u62e9", None))
        self.camera_selector.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.cameraButton1.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.cameraButton1.setText(QCoreApplication.translate("Widget", u"\u6253\u5f00\u6444\u50cf\u5934", None))
        self.cameraButton2.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.cameraButton2.setText(QCoreApplication.translate("Widget", u"\u5173\u95ed\u6444\u50cf\u5934", None))
        self.cameraview.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: rgb(0, 0, 0); border-image: url(:/Whalze/images/\u798f\u5dde\u5927\u5b66logo(\u7ea2).jpg);", None))
        self.simulator_group.setTitle(QCoreApplication.translate("Widget", u"3D\u4eff\u771f", None))
        self.simulator_enable_checkbox.setText(QCoreApplication.translate("Widget", u" \u542f\u7528\u4eff\u771f\u663e\u793a", None))
        self.open_simulator_button.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(213, 88.40%, 62.90%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.open_simulator_button.setText(QCoreApplication.translate("Widget", u"\u6253\u5f00\u4eff\u771f\u7a97\u53e3", None))
        self.update_simulator_button.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(213, 88.40%, 62.90%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.update_simulator_button.setText(QCoreApplication.translate("Widget", u"\u66f4\u65b0\u4eff\u771f", None))
        self.calibration_group.setTitle(QCoreApplication.translate("Widget", u"\u624b\u773c\u6807\u5b9a (\u76f8\u673a -- \u52a8\u5e73\u53f0)", None))
        self.label_trans_x.setText(QCoreApplication.translate("Widget", u"\u5e73\u79fb X (mm)", None))
        self.label_trans_y.setText(QCoreApplication.translate("Widget", u"\u5e73\u79fb Y (mm)", None))
        self.label_trans_z.setText(QCoreApplication.translate("Widget", u"\u5e73\u79fb Z (mm)", None))
        self.label_trans_r.setText(QCoreApplication.translate("Widget", u"\u65cb\u8f6c Roll (deg)", None))
        self.label_trans_p.setText(QCoreApplication.translate("Widget", u"\u65cb\u8f6c Pitch (deg)", None))
        self.label_trans_y_2.setText(QCoreApplication.translate("Widget", u"\u65cb\u8f6c Yaw (deg)", None))
        self.apply_transform_button.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.apply_transform_button.setText(QCoreApplication.translate("Widget", u"\u5e94\u7528\u53d8\u6362\u77e9\u9635", None))
        self.robot_control_group.setTitle(QCoreApplication.translate("Widget", u"\u673a\u5668\u4eba\u63a7\u5236", None))
        self.pushButton_3.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(123, 75.50%, 68.00%, 0.25); border-radius: 3px; border: 3px solid hsla(123, 75.50%, 68.00%, 0.25)", None))
        self.pushButton_3.setText(QCoreApplication.translate("Widget", u"\u590d\u4f4d", None))
        self.pushButton_2.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(14, 83.40%, 59.80%, 0.25); border-radius: 3px; border: 3px solid hsla(14, 83.40%, 59.80%, 0.25)", None))
        self.pushButton_2.setText(QCoreApplication.translate("Widget", u"\u6025\u505c", None))
        self.label_21.setText(QCoreApplication.translate("Widget", u"\u901f\u5ea6", None))
        self.v.setStyleSheet(QCoreApplication.translate("Widget", u"selection-background-color: hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_4.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_4.setText(QCoreApplication.translate("Widget", u"\u89c6\u89c9\u5206\u7c7b", None))
        self.pushButton_5.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_5.setText(QCoreApplication.translate("Widget", u"\u89c6\u89c9\u62fe\u53d6", None))
        self.pushButton_6.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_6.setText(QCoreApplication.translate("Widget", u"\u8fd0\u884c\u66f2\u7ebf", None))
        self.inch_group.setTitle(QCoreApplication.translate("Widget", u"\u5bf8\u52a8", None))
        self.pushButton_8.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_8.setText(QCoreApplication.translate("Widget", u"X+", None))
        self.pushButton_9.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_9.setText(QCoreApplication.translate("Widget", u"X-", None))
        self.pushButton_10.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_10.setText(QCoreApplication.translate("Widget", u"Y+", None))
        self.pushButton_11.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_11.setText(QCoreApplication.translate("Widget", u"Y-", None))
        self.pushButton_12.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_12.setText(QCoreApplication.translate("Widget", u"Z+", None))
        self.pushButton_13.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_13.setText(QCoreApplication.translate("Widget", u"Z-", None))
        self.jog_sequence_group.setTitle(QCoreApplication.translate("Widget", u"\u70b9\u52a8", None))
        self.start_point_label.setText(QCoreApplication.translate("Widget", u"\u521d\u59cb\u5750\u6807", None))
        self.start_x_spinbox.setSuffix(QCoreApplication.translate("Widget", u" mm", None))
        self.start_y_spinbox.setSuffix(QCoreApplication.translate("Widget", u" mm", None))
        self.start_z_spinbox.setSuffix(QCoreApplication.translate("Widget", u" mm", None))
        self.end_point_label.setText(QCoreApplication.translate("Widget", u"\u7ec8\u70b9\u5750\u6807", None))
        self.end_x_spinbox.setSuffix(QCoreApplication.translate("Widget", u" mm", None))
        self.end_y_spinbox.setSuffix(QCoreApplication.translate("Widget", u" mm", None))
        self.end_z_spinbox.setSuffix(QCoreApplication.translate("Widget", u" mm", None))
        self.run_jog_sequence_button.setText(QCoreApplication.translate("Widget", u"\u8fd0\u884c\u70b9\u52a8\u5e8f\u5217", None))
        self.motor_debug_group.setTitle(QCoreApplication.translate("Widget", u"\u7535\u673a\u8c03\u8bd5", None))
        self.pushButton_14.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_14.setText(QCoreApplication.translate("Widget", u"A+", None))
        self.pushButton_15.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_15.setText(QCoreApplication.translate("Widget", u"A-", None))
        self.pushButton_16.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_16.setText(QCoreApplication.translate("Widget", u"B+", None))
        self.pushButton_17.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_17.setText(QCoreApplication.translate("Widget", u"B-", None))
        self.pushButton_18.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_18.setText(QCoreApplication.translate("Widget", u"C+", None))
        self.pushButton_19.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_19.setText(QCoreApplication.translate("Widget", u"C-", None))
        self.kinematics_group.setTitle(QCoreApplication.translate("Widget", u"\u8fd0\u52a8\u5b66\u89e3\u7b97\u6d4b\u8bd5", None))
        self.label_fk.setText(QCoreApplication.translate("Widget", u"\u76ee\u6807\u672b\u7aef XYZ (mm)", None))
        self.ik_x.setSuffix(QCoreApplication.translate("Widget", u" mm", None))
        self.ik_y.setSuffix(QCoreApplication.translate("Widget", u" mm", None))
        self.ik_z.setSuffix(QCoreApplication.translate("Widget", u" mm", None))
        self.solve_ik_button.setText(QCoreApplication.translate("Widget", u"\u9006\u89e3 + \u6b63\u89e3\u9a8c\u8bc1", None))
        self.ik_result_label.setText(QCoreApplication.translate("Widget", u"\u89d2\u5ea6 / \u8bef\u5dee\uff1a--", None))
        self.vision_dynamic_checkbox.setText(QCoreApplication.translate("Widget", u"\u542f\u7528\u52a8\u6001\u8bc6\u522b", None))
        self.visualization_checkbox.setText(QCoreApplication.translate("Widget", u" \u542f\u7528\u66f2\u7ebf\u53ef\u89c6\u5316", None))
        self.pushButton_7.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.pushButton_7.setText(QCoreApplication.translate("Widget", u"\u6253\u5f00\u6c14\u6cf5", None))
        self.status_group.setTitle(QCoreApplication.translate("Widget", u"\u673a\u5668\u4eba\u72b6\u6001", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"\u6ed1\u53f0\u4f4d\u7f6e", None))
        self.label_10.setText(QCoreApplication.translate("Widget", u"A", None))
        self.textBrowser_3.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.label_12.setText(QCoreApplication.translate("Widget", u"B", None))
        self.textBrowser_4.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"C", None))
        self.textBrowser_5.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"\u52a8\u5e73\u53f0\u4f4d\u7f6e", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"X", None))
        self.textBrowser_6.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.label_16.setText(QCoreApplication.translate("Widget", u"Y", None))
        self.textBrowser_7.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.label_15.setText(QCoreApplication.translate("Widget", u"Z", None))
        self.textBrowser_8.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.calibrationStatus.setStyleSheet(QCoreApplication.translate("Widget", u"font-size: 12px; border: 1px solid gray; padding: 2px; background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.calibrationStatus.setText(QCoreApplication.translate("Widget", u"\u72b6\u6001: \u7b49\u5f85\u68c0\u6d4b...", None))
        self.writing_group.setTitle(QCoreApplication.translate("Widget", u"\u7ec8\u7aef\u8f93\u51fa", None))
        self.terminal_output.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.writing_control_label.setText(QCoreApplication.translate("Widget", u"\u5199\u5b57\u63a7\u5236:", None))
        self.input_method_label.setText(QCoreApplication.translate("Widget", u"\u8f93\u5165\u65b9\u5f0f:", None))
        self.input_method.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.text_input_label.setText(QCoreApplication.translate("Widget", u"\u8f93\u5165\u6587\u5b57:", None))
        self.text_input.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.text_input.setText(QCoreApplication.translate("Widget", u"FZU", None))
        self.font_size_label.setText(QCoreApplication.translate("Widget", u"\u5b57\u4f53\u5927\u5c0f:", None))
        self.writing_area_label.setText(QCoreApplication.translate("Widget", u"\u533a\u57df(mm)", None))
        self.z_height_label.setText(QCoreApplication.translate("Widget", u"\u5199\u5b57\u9ad8\u5ea6Z", None))
        self.writing_speed_label.setText(QCoreApplication.translate("Widget", u"\u5199\u5b57\u901f\u5ea6:", None))
        self.use_handwriting_button.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.use_handwriting_button.setText(QCoreApplication.translate("Widget", u"\u4f7f\u7528\u624b\u5199", None))
        self.preview_button.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.preview_button.setText(QCoreApplication.translate("Widget", u"\u9884\u89c8\u8f68\u8ff9", None))
        self.start_writing_button.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(123, 75.50%, 68.00%, 0.25); border-radius: 5px; border: 1px solid hsla(123, 75.50%, 68.00%, 0.94)", None))
        self.start_writing_button.setText(QCoreApplication.translate("Widget", u"\u5f00\u59cb\u5199\u5b57", None))
        self.stop_writing_button.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(14, 83.40%, 59.80%, 0.25); border-radius: 5px; border: 1px solid hsla(14, 83.40%, 59.80%, 0.94)", None))
        self.stop_writing_button.setText(QCoreApplication.translate("Widget", u"\u505c\u6b62\u5199\u5b57", None))
        self.clear_canvas_button.setStyleSheet(QCoreApplication.translate("Widget", u"background-color: hsla(0, 0.00%, 49.00%, 0.25); border-radius: 5px; border: 1px solid hsla(213, 88.40%, 62.90%, 0.94)", None))
        self.clear_canvas_button.setText(QCoreApplication.translate("Widget", u"\u6e05\u7a7a\u753b\u5e03", None))
        self.writing_canvas_label.setText(QCoreApplication.translate("Widget", u"\u5199\u5b57\u8f68\u8ff9\u9884\u89c8 (\u53ef\u624b\u5199):", None))
        self.writing_status.setStyleSheet(QCoreApplication.translate("Widget", u"font-size: 12px; border: 1px solid gray; padding: 2px;", None))
        self.writing_status.setText(QCoreApplication.translate("Widget", u"\u72b6\u6001: \u5c31\u7eea", None))
    # retranslateUi

